### PR TITLE
Adjust floating-point rounding direction

### LINKED ISSUE #1124: Block locator size unit test failure.
```
make  check-TESTS
make[1]: Entering directory '/home/verbus/build-libbitcoin/libbitcoin'
make[2]: Entering directory '/home/verbus/build-libbitcoin/libbitcoin'
FAIL: libbitcoin-test_runner.sh
========================================
   libbitcoin 3.4.0: ./test-suite.log
========================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: libbitcoin-test_runner.sh
===============================

FAIL libbitcoin-test_runner.sh (exit status: 201)

============================================================================
Testsuite summary for libbitcoin 3.4.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to eric@voskuil.org
============================================================================
make[2]: *** [Makefile:6032: test-suite.log] Error 1
make[2]: Leaving directory '/home/verbus/build-libbitcoin/libbitcoin'
make[1]: *** [Makefile:6140: check-TESTS] Error 2
make[1]: Leaving directory '/home/verbus/build-libbitcoin/libbitcoin'
make: *** [Makefile:6347: check-am] Error 2
Running 1901 test cases...
Platform: linux
Compiler: GNU C++ version 9.1.0
STL     : GNU libstdc++ version 20190503
Boost   : 1.62.0
test/chain/block.cpp(71): fatal error: in "chain_block_tests/block__locator_size__positive_backoff__returns_log_plus_eleven": critical check 18u == chain::block::locator_size(top) has failed [18 != 19]

real	13m15.612s
user	41m36.402s
sys	3m6.667s
```

### PR DESCRIPTION
**Pull request by thecodefactory**
Adjust floating-point rounding direction for better consistency across platforms (resolves #1124).

### CODE REVIEW

**Comment by evoskuil** [comment]
This will have an impact on intended behavior.

**Comment by thecodefactory** [comment]
> This will have an impact on intended behavior.

@evoskuil No worries, I wasn't going to merge this, just wanted a starting point for a proper fix.  This is one of two possible rounding related changes that _appear_ to resolve the issue (as mentioned in #1124), but I'm not sure that either is correct or desired.  Comments, suggestions, or other approaches welcome.

**Comment by evoskuil** [comment]
The problem requires that we round up (or down and add 1). The objective is to always a locator size that represents a chain at least as long as the one provided, using standard locator construction. If we use nearest rounding we could be above or below.

**Comment by evoskuil** [comment]
Status?

**Comment by evoskuil** [comment]
Simply adding 0.5 to the log2 result (which must be positive) and truncating with a static cast to `size_t` should be sufficient.

**Comment by evoskuil** [comment]
See: https://github.com/libbitcoin/libbitcoin-system/pull/1144

**Pull request closed without merging**
