### PR TITLE
Consolidate dictionaries, match full Electrum and bip39 lists, rename seed.

### PR DESCRIPTION
**Pull request by evoskuil**

### CODE REVIEW

**Comment by evoskuil** [comment]
Yes

**Comment by mxaddict** [comment]
> Yes

Was it related to performance during compilation or just general clean up?

**Comment by evoskuil** [comment]
It pertains to the desired const and compile time construction of a single data structure that overlays the memory of the object code.

**Comment by mxaddict** [comment]
I see, thanks 👍🏼

**Comment by evoskuil** [comment]
No problem, see also: https://github.com/libbitcoin/libbitcoin-system/blob/master/include/bitcoin/system/impl/words/dictionary.ipp#L35-L40

**Pull request merged**
