### PR TITLE
Update boost, secp256k1 & m4; drop libpng, libz & qrencode; add tiff & embed qrencode.

### PR DESCRIPTION
**Pull request by evoskuil**

### CODE REVIEW

**Comment by kulpreet** [comment]
Boost 1.72! :tada:

**Comment by evoskuil** [comment]
0MQ next

**Comment by evoskuil** [comment]
Still some work to do.

**Comment by evoskuil** [comment]
As of boost 1.72.0 (the version in the PR) the `ICU_LINK` symbol is no longer supported and produces a hard stop. See tags here: https://github.com/boostorg/regex/commit/fc4dc17dc745a9fc4ab1849cef3710354a6b7782

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-system/issues/1192

**Pull request merged**
