### PR TITLE
fail configure if libraries not found

### PR DESCRIPTION
**Pull request by xloem**
otherwise there are build errors later

### CODE REVIEW

**Comment by evoskuil** [comment]
Thanks, but see top of file, this is generated code. Changes must be applied in libbitcoin-build. Also I’m pretty sure the existing implementation would fail immediately on missing dependencies, so I’m not sure what this changes.

**Comment by xloem** [comment]
I wasn't getting immediate failure (what would trigger the failure?); i was getting compile errors because my libicu was too old.  I'll visit libbitcoin-build.

**Comment by xloem** [comment]
I've submitted https://github.com/libbitcoin/libbitcoin-build/pull/224 .

**Comment by xloem** [comment]
note: it doesn't say at the top of configure.ac specifically, that it is generated

**Comment by thecodefactory** [comment]
I see a generated notice on both version3 and master:

```
###############################################################################
#  Copyright (c) 2014-2015 libbitcoin developers (see COPYING).
#
#         GENERATED SOURCE CODE, DO NOT EDIT EXCEPT EXPERIMENTALLY
#
###############################################################################
```

**Comment by xloem** [comment]
My error again.  I was viewing the changes and didn't realize I had to click the expand button multiple times to see the whole top of the file.

**Pull request closed without merging**
